#!/usr/bin/env bash
# Pull + save handoff images for air-gapped / offline Kubernetes transfer.
#
# On a machine WITH Docker Hub access:
#   ./handoff/k8s-deploy/mirror-images.sh
#   # or: OUT_DIR=/tmp/llm-images ./handoff/k8s-deploy/mirror-images.sh
#
# Copy the resulting *.tar files to the air-gapped site, then import
# (see README «Air-gap / mirror»).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="${OUT_DIR:-${ROOT}/offline-images}"
STAMP="$(date +%Y%m%d)"
mkdir -p "${OUT_DIR}"

# Override with env if your Hub tags differ.
GATEWAY_IMAGE="${GATEWAY_IMAGE:-mohammadmoazami007007/llm_proxy:latest}"
OCR_IMAGE="${OCR_IMAGE:-mohammadmoazami007007/llmocr:latest}"
POSTGRES_IMAGE="${POSTGRES_IMAGE:-postgres:16-alpine}"
REDIS_IMAGE="${REDIS_IMAGE:-redis:7-alpine}"

INCLUDE_OCR="${INCLUDE_OCR:-1}"

IMAGES=(
  "${GATEWAY_IMAGE}"
  "${POSTGRES_IMAGE}"
  "${REDIS_IMAGE}"
)
if [[ "${INCLUDE_OCR}" == "1" ]]; then
  IMAGES+=("${OCR_IMAGE}")
fi

safe_name() {
  echo "$1" | sed 's|/|_|g; s|:|_|g'
}

echo "==> Output directory: ${OUT_DIR}"
for img in "${IMAGES[@]}"; do
  echo "==> Pull ${img}"
  docker pull "${img}"
  out="${OUT_DIR}/$(safe_name "${img}")_${STAMP}.tar"
  echo "==> Save ${img} -> ${out}"
  docker save "${img}" -o "${out}"
  ls -lh "${out}"
done

MANIFEST="${OUT_DIR}/manifest_${STAMP}.txt"
{
  echo "# llm_fastapi handoff image mirror ${STAMP}"
  echo "# Generated by mirror-images.sh"
  for img in "${IMAGES[@]}"; do
    digest="$(docker image inspect "${img}" --format '{{index .RepoDigests 0}}' 2>/dev/null || true)"
    id="$(docker image inspect "${img}" --format '{{.Id}}')"
    echo "${img}"
    echo "  id=${id}"
    echo "  digest=${digest:-n/a}"
    echo "  tar=$(safe_name "${img}")_${STAMP}.tar"
    echo
  done
} > "${MANIFEST}"

echo "==> Wrote ${MANIFEST}"
echo "==> Transfer ${OUT_DIR}/*.tar to the air-gapped cluster and follow README air-gap steps."
