#!/usr/bin/env bash
# Build and push llm_proxy (gateway) for Kubernetes.
#
# Usage:
#   REGISTRY=registry.example.com/myproj TAG=1.0.0 ./scripts/k8s_push_gateway_image.sh
#   REGISTRY=ghcr.io/org ./scripts/k8s_push_gateway_image.sh   # TAG defaults to git short sha or latest
#
# Then set in k8s/team-b/kustomization.yaml:
#   images:
#     - name: llm_proxy
#       newName: ${REGISTRY}/llm_proxy
#       newTag: ${TAG}
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT}"

if [[ -z "${REGISTRY:-}" ]]; then
  echo "ERROR: set REGISTRY, e.g. REGISTRY=registry.company.local/llm" >&2
  exit 1
fi

TAG="${TAG:-}"
if [[ -z "${TAG}" ]]; then
  if git rev-parse --short HEAD >/dev/null 2>&1; then
    TAG="$(git rev-parse --short HEAD)"
  else
    TAG="latest"
  fi
fi

IMAGE="${REGISTRY}/llm_proxy:${TAG}"
IMAGE_LATEST="${REGISTRY}/llm_proxy:latest"

echo "==> Building ${IMAGE}"
docker build -t "${IMAGE}" -t "${IMAGE_LATEST}" .

echo "==> Pushing ${IMAGE}"
docker push "${IMAGE}"
docker push "${IMAGE_LATEST}"

PATCH_FILE="${ROOT}/k8s/team-b/kustomization.image.env"
cat > "${PATCH_FILE}" <<EOF
# Generated by k8s_push_gateway_image.sh — merge into kustomization.yaml images:
#   - name: llm_proxy
#     newName: ${REGISTRY}/llm_proxy
#     newTag: "${TAG}"
REGISTRY=${REGISTRY}
TAG=${TAG}
IMAGE=${IMAGE}
EOF

echo "==> Pushed ${IMAGE}"
echo "==> Update k8s/team-b/kustomization.yaml images.newName/newTag then:"
echo "    kubectl apply -k k8s/team-b/"
echo "==> Wrote ${PATCH_FILE}"
